<?php
defined('BASEPATH') OR exit('No direct script access allowed');
?><!DOCTYPE html>
<html lang="en">
  <head>
    <title>ECS Forum</title>

    <!-- Main styles-->
    <link rel="stylesheet" href="/styles/style.css" />
  </head>
  <body>

    <!-- This login box is shown whenever the server denies access to a resource via
    401 error -->
    <div id="login_form" onsubmit="runLogin(this,event);">
      <form>
        <h1>Login</h1>

        <!-- Hidden by default in the CSS - JavaScript will display this if there's a problem -->
        <div id="login_error">
          The username / password you entered was incorrect!
        </div>

        <div class="box">
          <label>Username:</label>
          <input type="text" id="username" />
        </div>

        <div class="box">
          <label>Password:</label>
          <input type="password" id="password" />
        </div>

        <input type="submit" value="Login" />
      </form>
    </div>

    <header>
      <h1>ECS Forum</h1>
      <img src="" alt="Profile" id="pic" />
      <div id="name"></div>
    </header>

    <!-- List of registered modules goes here (generated by the JavaScript) -->
    <nav id="sidebar"></nav>

    <!-- Content goes here (generated by the JavaScript) -->
    <main id="main">
      <h2 id="title"></h2>
      <span id="desc" class="details"></span>
      <div id="header"></div>
      <div id="rows"></div>
      <div id="footer"></div>
    </main>

    <!-- JavaScript blocks rendering while it is being loaded so we put it at the end of the page -->
    <script src="/scripts/jquery.min.js"></script>
    <script src="/scripts/script.js"></script>
    <script src="/scripts/ckeditor/ckeditor.js"></script>
  </body>
</html>